name: Thurles Squash Website
favicon: null
layout_spectrum: 0.39086983958259225
typography_spectrum: 0.46229500393383205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.35641598515212536
  lightness: 0.8964421825949103
  saturation: 0.7218821526039392
  rhythmicContrast: 0.12758886814117432
purpose: []
